#!/bin/bash
#
# This script runs the image generated by the docker build script
# using docker run command, where:
#   --rm  automatically removes the container and on exit
#   -i  keeps the standard input open
#   -t  provides a terminal as a interactive shell within container
#   --volumes  are file systems mounted on docker container to preserve
# data generated during the yocto build and these are stored on the host.
# Left side being an absolute path on the host machine, right side being
# an absolute path inside the container.
#
#   $ ./docker-run.sh
#

# source the common variables
. ./imx-5.15.71-2.2.0/env.sh

# container name
CONTAINER_NAME="imx6ull-yocto"

# run the docker image
if docker inspect ${CONTAINER_NAME} >/dev/null 2>&1; then
    echo enter a container
    docker start ${CONTAINER_NAME}
    docker exec -it --user $(id -u):$(id -g) ${CONTAINER_NAME} /bin/bash
else
    echo create a new container
    docker run -it \
        --name ${CONTAINER_NAME} \
        --user $(id -u):$(id -g) \
        --volume ${HOME}:${HOME} \
        --volume ${DOCKER_WORKDIR}:${DOCKER_WORKDIR} \
        --volume $(pwd)/${IMX_RELEASE}:${DOCKER_WORKDIR}/${IMX_RELEASE} \
        "${DOCKER_IMAGE_TAG}" \
        $1
fi
